version: "3.3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ajinomoto-be_api
    ports:
      - 8093:8093
    volumes:
      - ./.env:/app/.env:Z
      - ../files:/app/files/:Z
